---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-mq
  labels:
    app: gdi
    component: storage
    element: message-queue
spec:
  image: rabbitmq:3.11.10-management-alpine
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /etc/rabbitmq/definitions.json
                    subPath: defs.json
                    name: definitions
            volumes:
              - name: definitions
                configMap:
                  name: mq-definitions
  rabbitmq:
    additionalConfig: |
      listeners.tcp.default = 5672
      disk_free_limit.absolute = 1GB
      management.tcp.port = 15672
      load_definitions = /etc/rabbitmq/definitions.json
      default_vhost = /
